### ISSUE TITLE
What to use for latest published version?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/cg-reports#10]
Is the process the same as publishing specs, so for a latest version the path would be something like:

```https://www.w3.org/community/reports/<cgshortname>/<reportshortname>```

If not, what do we use? Respec gives an error on a CG-FINAL without a latestVersion.

I looked at the published notes for credentials, but they all list the dated current URL as the latest version, which would mean if the note gets republished no one landing at the old note will find their way forward.

Or is there a process for removing old notes and redirecting to the new ones when they're published that isn't mentioned yet?

**Comment by coolharsh55** [comment]
The assumption ReSpec makes is that there is a w3 url assigned to the group which points to the latest version (and also because the tool is primarily concerned with w3c specs). The exported HTML does not show the error, so I think you can edit the latest version info to whatever PURL the group is using.

**Comment by mattgarrish** [comment]
So, just to confirm, this publishing method will add the dated report to the community group's home page, same as going through the "Publish Report" button?

And in that case, the idea is that by pointing the latest version link to the CG home page users can go through the final report list to find if there is a newer version, correct?

**Comment by coolharsh55** [comment]
Sorry, let me clarify what I meant. In DPVCG, we use https://w3id.org/dpv as the PURL for the specs. So in the ReSpec output, the latest version uses URLS starting with this. I guess you can use the CG homepage or other page url as well. Though do note I'm not part of the W3C admin staff, so my suggestions are not authoritative.

**Comment by mattgarrish** [comment]
> In DPVCG, we use https://w3id.org/dpv as the PURL for the specs. So in the ReSpec output, the latest version uses URLS starting with this.

Thanks for the explanation. This is what I was hoping we could avoid with this process, as then it requires the CG to create and maintain these identifiers. Seems like it could lead to a lot of variation in how groups operate.

W3C automatically adds redirects on specification shortnames, so, for example, https://www.w3.org/TR/<shortname> takes you to the latest version of whatever standard you name. There's nothing the WG has to do beyond making the various publishing requests.

I was hoping something similar was in place for the CG reports, but it doesn't sound like the case.

> I'm not part of the W3C admin staff, so my suggestions are not authoritative.

Appreciate that someone responded! 😄 It at least gives some ideas on possible alternative ways forward with this.

**Comment by coolharsh55** [comment]
CGs can request a w3 PURL for their outputs. For example, we had https://w3.org/ns/dpv which still works, but switched to https://w3id.org.dpv because we wanted quicker turnaround (e.g. we have something like ~20 documents) and going through the w3 request process was taking a lot of time. If its important for the group to have no ReSpec errors in the final output, I suggest raising an issue in the ReSpec repo to take out that error for latest version.

**Comment by iherman** [comment]
At this moment, the only solution I see, and that can be used right away, is to set up redirection from, say:

`https://www.w3.org/ns/<cgshortname>/<reportshorname>`

to the newest version of a CG document. This can be done by creating the `cgshortname` directory under `/ns`, and add a simple `.htaccess` file. The downside is that the `.htaccess` file has to be manually updated and uploaded to the server by a W3C team member; I do not think anybody else can have access to such files. It is not a big deal, but it is a small extra chore. (Obviously, we could also use date space for the same purpose, but `/ns` seems to be more natural.)

Are there plans to make it more automatic, @dontcallmedom @deniak @vivienlacourba ? Would it be very complicated to set up such a redirection automatically on `https://www.w3.org/community/reports/`, or, at least, to offer a mechanism whereby at least a team member can do such a manipulation to avoid the usage of `/ns`?

**Comment by dontcallmedom** [comment]
tagging @ianbjacobs as well

**Comment by iherman** [comment]
Ping @dontcallmedom @deniak @vivienlacourba @ianbjacobs any update on this issue? The Publishing CG has a number of reports we would like to properly publish; I can go down the `/ns` road, it is not a terribly big deal, but if there is a better way I am all for it...

cc @mattgarrish

**Comment by ianbjacobs** [comment]
Hi all,

The CG publishing system assumes a "living draft" approach: the URL that you provide to the system via the CG's home page --a button accessible to the chairs-- is a "latest version URL". 

When the time comes to publish a Final Specification, there is an expectation that a different URL will be used for that unchanging document. 

When you use the CG publishing system, both Drafts and Final Specifications are linked from the top of the CG's home page. 

Once you have a Final Specification, you can do a number of things:

* Include a link to it from the Draft (that is, the document available through the original latest version URL).
* Point people to the CG's home page, where the Final Specification will be listed.

Please let me know if this answers your questions,

Ian

**Comment by iherman** [comment]
Thanks @ianbjacobs. However, I do not think answers our question. For example, when you say:

Let me take a specific example. This repository has a series of reports generated by the Data Privacy Vocabulary and Controls CG. E.g., 

https://www.w3.org/community/reports/dpvcg/CG-FINAL-dpv-gdpr-20221205/

I am looking at the home page of the group:

https://www.w3.org/community/dpvcg/

and, indeed, there is a table to refer to the documents there. So far so good. 

However the table uses the Dated URLs as targets (ie, the one above). What we are looking for is a stable _undated_ URL-s because FINAL reports may also change, just like Recs or Notes change. The DPVCG uses

https://w3id.org/dpv/dpv-gdpr

as an undated, ie, stable URL; what we are looking for such undated URL-s for the Publishing CG reports. The DPVCG uses an external URL service for this; we would prefer to have a stable ***W3C*** URL. So far the only approach that seems to exist for us is to manually curate a `.htaccess` file somewhere (e.g., under `/publishing/`) and this issues wonders whether W3C could provide such a service in general.

(If not, we can live with the pedestrian approach of `.htaccess`. But we preferred to ask...)

**Comment by ianbjacobs** [comment]
Hi Ivan,

We do not currently have special mechanisms for LV URIs for Final Reports. Some alternatives:

* In each report, include this: “For the latest Final Report, see the group’s home page.” 
* When a Final Report is no longer the latest, update it in place with a message to the user, à la:
  https://www.w3.org/TR/2013/PR-prov-o-20130312/

I realize that does not scale well for a large number of Final Reports. I don’t think we anticipated a long
succession of Final Reports when we designed our tools.

Ian

> On Mar 4, 2023, at 1:57 AM, Ivan Herman ***@***.***> wrote:
> 
> 
> Thanks @ianbjacobs. However, I do not think answers our question. For example, when you say:
> Let me take a specific example. This repository has a series of reports generated by the Data Privacy Vocabulary and Controls CG. E.g.,
> https://www.w3.org/community/reports/dpvcg/CG-FINAL-dpv-gdpr-20221205/
> I am looking at the home page of the group:
> https://www.w3.org/community/dpvcg/
> and, indeed, there is a table to refer to the documents there. So far so good.
> However the table uses the Dated URLs as targets (ie, the one above). What we are looking for is a stable undated URL-s because FINAL reports may also change, just like Recs or Notes change. The DPVCG uses
> https://w3id.org/dpv/dpv-gdpr
> as an undated, ie, stable URL; what we are looking for such undated URL-s for the Publishing CG reports. The DPVCG uses an external URL service for this; we would prefer to have a stable W3C URL. So far the only approach that seems to exist for us is to manually curate a .htaccess file somewhere (e.g., under /publishing/) and this issues wonders whether W3C could provide such a service in general.
> (If not, we can live with the pedestrian approach of .htaccess. But we preferred to ask...)
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

--
Ian Jacobs ***@***.***>
https://www.w3.org/People/Jacobs/
Tel: +1 917 450 8783

**Comment by iherman** [comment]
That's all right; it was worth asking, though... We will come up with a publ. CG mechanism.

@mattgarrish we should take this back to our mailing list.
